core/urls.py
from django.urls import path
from .views import HomeView, OrderSummaryView, ItemDetailView, checkout, view_profile, orders_view, add_to_cart, remove_from_cart, SearchResults, confirm_order, thank_you
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item-list'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', checkout.as_view(), name='checkout-page'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('confirm-order/', confirm_order, name='confirm-order'),
    path('thank_you/', thank_you, name="thank-you"),
    path('profile/', view_profile, name="profile-view"),
    path('orders/', orders_view, name="orders-view"),

    path('search/', SearchResults.as_view(), name="search_results"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

giftshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls'), name='core'),
]

templates/base.html
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <!-- Google Web Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" /> 

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

  <!-- Libraries Stylesheet -->
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />

  <!-- Customized Bootstrap Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body>

    {% include "navbar.html" %}

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js-na1.hs-scripts.com/23710000.js"></script>
    <!-- End of HubSpot Embed Code -->
    
  </body>
</html>

templates/footer.html
  <!-- Footer Start -->
  <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">Gift</span>Tribute</h1>
            </a>
            <p>Only place to get your loved ones the most pleasent surprise</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Noida</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+91 92893 49557</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="{% url 'core:order-summary' %}"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="{% url 'core:order-summary' %}"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">Giftribute</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="img/payments.png" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

templates/navbar.html
{% load static %}

<head>
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <style>
        /* Style for search input */
        input[type="search"] {
            background-color: transparent;
            border: none;
            border-bottom: 2px solid #ccc;
            padding: 10px;
            width: 100%;
            font-size: 16px;
            color: #333;
        }
    </style>
</head>

    <!-- Topbar Start -->
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="" class="text-decoration-none pl-3">
                <img src="{% static 'img/logo.png' %}" alt="logo" width="70%" />
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form action="{% url 'core:search_results' %}"  method="get">
                <div class="input-group">
                    <input type="search" name="q" class="form-control ml-auto mr-auto" placeholder="Search for products" class="form-control">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                {% comment %} <span class="badge">0</span> {% endcomment %}
            </a>
            <a href="{% url 'core:order-summary' %}" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                {% comment %} <span class="badge">0</span> {% endcomment %}
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">
            <div class="col-lg">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none pl-3" style="width: 50%">
                        <img src="{% static 'img/logo.png' %}" alt="logo" width="70%" />
                    </a>
                    <button type="button" class="navbar-toggler sidebar_button" data-toggle="collapse" data-target="#sidebar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    {% if user.is_authenticated %}
                        <div class="collapse navbar-collapse justify-content-between mb-3 mt-3" id="navbarCollapse">
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'core:profile-view' %}" class="nav-item nav-link">Profile</a>
                                <a href="{% url 'core:orders-view' %}" class="nav-item nav-link">Orders</a>
                                <a href="{% url 'account_change_password' %}" class="nav-item nav-link">Change Password</a>
                                <a href="{% url 'account_logout' %}" class="nav-item nav-link">Logout</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="collapse navbar-collapse justify-content-between mb-3 mt-3" id="navbarCollapse">
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'account_login' %}" class="nav-item nav-link">Login</a>
                                <a href="{% url 'account_signup' %}" class="nav-item nav-link">Register</a>
                            </div>
                        </div>
                    {% endif %}
                    <!-- categories section mobile start -->
                <div id="sidebar" class="sidebar mobile_view collapse">
                    <div class="sidebar-top">
                        <button type="button" class="navbar-toggler sidebar_button" data-toggle="collapse" data-target="#sidebar">
                            <i class="fas fa-times"></i>
                        </button>
                        <ul class="nav_list">
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Bags">
                                    <span class="links_name">Bags</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Pastery">
                                    <span class="links_name">Pastery</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Candles">
                                    <span class="links_name">Candles</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Pottery">
                                    <span class="links_name">Pottery</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Valentine">
                                    <span class="links_name">Valentine's</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Rose">
                                    <span class="links_name">Rose</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Comics">
                                    <span class="links_name">Comics</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Teddy">
                                    <span class="links_name">Teddy</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Cushions">
                                    <span class="links_name">Cushions</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Couples">
                                    <span class="links_name">Couples</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:search_results' %}?q=Bubu Dudu">
                                    <span class="links_name">Bubu Dudu</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="authentication_buttons">
                            <span class="auth_buttons"><a href="{% url 'core:profile-view' %}">Profile</a></span>
                            <span class="auth_buttons"><a href="{% url 'core:orders-view' %}">Orders</a></span>
                            <span class="auth_buttons"><a href="{% url 'account_change_password' %}">Change Password</a></span>
                            <span class="auth_buttons"><a href="{% url 'account_logout' %}">Logout</a></span>
                        </div>
                    {% else %}
                        <div class="authentication_buttons">
                            <span class="auth_buttons"><a href="{% url 'account_login' %}">Login</a></span>
                            <span class="auth_buttons"><a href="{% url 'account_signup' %}">Signup</a></span>
                        </div>
                    {% endif %}
                </div>


                <!-- categories section mobile end -->
                </nav>

                <!-- Categories Section desktop start -->
                <div class="col-lg category-section desktop_view">
                    <a class="btn categories-tab shadow-none align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                        <h6 class="m-0">Categories</h6>
                        <i class="fa fa-angle-down text-dark"></i>
                    </a>
                    <nav class="collapse show navbar navbar-light p-0" id="navbar-vertical">
                        <div class="navbar-nav category-nav w-100">
                            <a href="{% url 'core:search_results' %}?q=Teddy" class="nav-item category-nav-item nav-link">Teddy</a>
                            <a href="{% url 'core:search_results' %}?q=Cushions" class="nav-item category-nav-item nav-link">Cushions</a>
                            <a href="{% url 'core:search_results' %}?q=Couples" class="nav-item category-nav-item nav-link">Couples</a>
                            <a href="{% url 'core:search_results' %}?q=Bubu Dudu" class="nav-item category-nav-item nav-link">Bubu Dudu</a>
                            <a href="{% url 'core:search_results' %}?q=Comics" class="nav-item category-nav-item nav-link">Comics</a>
                            <a href="{% url 'core:search_results' %}?q=Rose" class="nav-item category-nav-item nav-link">Rose</a>
                            <a href="{% url 'core:search_results' %}?q=Valentine" class="nav-item category-nav-item nav-link">Valentine's</a>
                            <a href="{% url 'core:search_results' %}?q=Pottery" class="nav-item category-nav-item nav-link">Pottery</a>
                            <a href="{% url 'core:search_results' %}?q=Candles" class="nav-item category-nav-item nav-link">Candles</a>
                            <a href="{% url 'core:search_results' %}?q=Bags" class="nav-item category-nav-item nav-link">Bags</a>
                            <a href="{% url 'core:search_results' %}?q=Pastery" class="nav-item category-nav-item nav-link">Pastery</a>
                        </div>
                    </nav>
                </div>
                <!-- Categories section desktop end -->
          </div>
        </div>
      </div>


            </div>
        </div>
    </div>
    <!-- Navbar End -->
</div>

templates/order-summary.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Cart Start -->
<h2>Order Summary</h2>
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for order_item in object.items.all %}
                        <tr>
                            <td class="align-middle"><img src="{{order_item.item.image.all.first.image.url}}" alt="{{order_item.item.title}}" style="width: 50px;">{{order_item.item.title}}</td>
                            
                            {% if order_item.item.discount_price %}
                                <td class="align-middle">₹{{order_item.item.discount_price}} (Amount saved: {{order_item.get_saved_amount}})</td>
                            {% else %}
                                <td class="align-middle">₹{{order_item.item.price}}</td>
                            {% endif %}

                            <td class="align-middle">{{order_item.quantity}}</td>
                            <td class="align-middle">₹{{order_item.get_final_price}}</td>
                            <td class="align-middle"><a class="btn btn-sm btn-primary" href="{{order_item.item.get_remove_from_cart_url}}"><i class="fa fa-times"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            {% if object.get_total %}
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">₹{{object.get_total}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">₹{{object.get_total}}</h5>
                    </div>
                    <a class="btn btn-block btn-primary my-3 py-3" href="{% url 'core:checkout-page' %}">Proceed To Checkout</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Cart End -->
{% endblock content %}

templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/user.css'%}">
</head>
<!-- Header start -->
<header class="header">
    <div class="name-location">
      <h1>{{user.username}}</h1>
      <h6>{{user.email}}</h6>
      
    </div>
    
    <div class="signout">
      <button class="sign-out-button">SIGN OUT</button>
    </div>
   
  </header>
<!-- Header End -->

<!-- main content start -->
<div class="user-main-container">
    <!-- sidebar start -->
    <div class="sidebar">
        <div class="sidebar-desktop">
            <ul>
                <a href="{% url 'core:profile-view' %}"><li>Profile</li></a>
                <a href="{% url 'core:orders-view' %}"><li style="border:1.3px solid black;">Order</li></a>
                <a href=""><li>Offer</li></a>
            </ul>
        </div>
        <div class="sidebar-mobile">
            <button class="dropbtn">Options <i class="fas fa-angle-down"></i></button>
            <div class="dropdown-content">
               <a href="{% url 'core:profile-view' %}"><li style="border:1.3px solid black;">Profile</li></a>
               <a href="{% url 'core:orders-view' %}"><li>Order</li></a>
               <a href=""><li>Offer</li></a>
            </div>
          </div>                  
    </div>
    <!-- sidebar end -->
    
    <!-- order content start -->
    <div class="order-container">
        <div class="container-heading">
            <h2>Orders</h2>
            <span>{{ orders.count }} items</span>
        </div>
        {% for order in orders %}
            <div class="order-item-container">
                <div class="order-detail">
                    {% for item in order.items.all %}
                    <h3>{{item}}</h3>
                    {% endfor %}
                    <a href="#">view order <i class="fas fa-arrow-right"></i></a>
                </div>
                {% if order.delivered %}
                    <span class="order-status"><i class="fas fa-circle order-status-cancel" style='color:#31d41c'></i>Delivered</span>
                {% else %}
                    <span class="order-status"><i class="fas fa-circle order-status-cancel"></i>On the way</span>
                {% endif %}
                {% comment %} <div class="order-images">
                    <img src="./img/order-1.jpg" alt="order-image">
                    <img src="./img/order-2.jpg" alt="order-image">
                </div> {% endcomment %}
            </div>
        {% endfor %}
    </div>
    <!-- order content end -->
    
</div>

{% endblock %}

templates/payment_failure.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{{text}}

{% endblock content %}

templates/payment_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

Thank you for ordering, payment id: {{payment_id}}, order_id: {{}}

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

templates/search.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<head>
    <style>
        .product-img img {
          height: 275px;
          width: 100px;
        }
      
        @media (max-width: 767px) {
          .product-img img {
            height: 275px;
            width: 75px;
          }
          .card {
            padding-right: 2rem;
            padding-left: 2rem;
            padding-bottom: 1rem;
          }
        }
      </style>
</head>

<!-- Products Start -->
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Searched Products</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">

      {% for item in items %}
          <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
              <div class="card product-item border-0 mb-4 ">
                <div class="pr">
                  <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                      <a href="{{ item.get_absolute_url }}">
                        <img class="img-fluid w-100" src="{{ item.image.all.first.image.url }}" alt="">
                      </a>
                  </div>
                  <div class="bottom">
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">{{item.title}}</h6>
                        <div class="d-flex justify-content-center">
                            <h6>{{item.price}}</h6><h6 class="text-muted ml-2">
                                {% if item.discount_price %}
                                    <del>{{item.discount_price}}</del>
                                {% endif %}
                            </h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="{{ item.get_absolute_url }}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="{{ item.get_add_to_cart_url }}" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>
                </div>
              </div>
          </div>
        {% endfor %}
    </div>
</div>
<!-- Products End -->
{% endblock content %}

templates/thank_you.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Thank You for ordering with us. The pleasent gift is on it's way. Till then you can checkout our other <a href="{% url 'core:item-list' %}">products</h1></a>
<h2>Order Id: <a href = "https://giftributeshop.shiprocket.co/">{{order.order_id}}</a></h2>
{% endblock content %}